# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainFrame.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1438, 870)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setContentsMargins(-1, 0, 0, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setStyleSheet("QGroupBox\n"
"{\n"
"  border:0px;\n"
"}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(919, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_min = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_min.setMinimumSize(QtCore.QSize(30, 21))
        self.pushButton_min.setMaximumSize(QtCore.QSize(30, 21))
        self.pushButton_min.setText("")
        self.pushButton_min.setObjectName("pushButton_min")
        self.horizontalLayout.addWidget(self.pushButton_min)
        self.pushButton_mid = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_mid.setMinimumSize(QtCore.QSize(30, 21))
        self.pushButton_mid.setMaximumSize(QtCore.QSize(30, 21))
        self.pushButton_mid.setText("")
        self.pushButton_mid.setObjectName("pushButton_mid")
        self.horizontalLayout.addWidget(self.pushButton_mid)
        self.pushButton_close = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_close.setMinimumSize(QtCore.QSize(30, 21))
        self.pushButton_close.setMaximumSize(QtCore.QSize(30, 21))
        self.pushButton_close.setText("")
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout.addWidget(self.pushButton_close)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setStyleSheet("QGroupBox\n"
"{\n"
"   border-color: rgb(78, 78, 78);\n"
"}\n"
"\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setSpacing(50)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_main = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_main.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_main.setText("")
        self.pushButton_main.setCheckable(True)
        self.pushButton_main.setObjectName("pushButton_main")
        self.verticalLayout.addWidget(self.pushButton_main)
        self.pushButton_light = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_light.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_light.setText("")
        self.pushButton_light.setCheckable(True)
        self.pushButton_light.setObjectName("pushButton_light")
        self.verticalLayout.addWidget(self.pushButton_light)
        self.pushButton_tempature = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_tempature.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_tempature.setText("")
        self.pushButton_tempature.setCheckable(True)
        self.pushButton_tempature.setObjectName("pushButton_tempature")
        self.verticalLayout.addWidget(self.pushButton_tempature)
        self.pushButton_reserve = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_reserve.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_reserve.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_reserve.setObjectName("pushButton_reserve")
        self.verticalLayout.addWidget(self.pushButton_reserve)
        spacerItem1 = QtWidgets.QSpacerItem(20, 305, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, 11, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setStyleSheet("QGroupBox\n"
"{\n"
"   border-color: rgb(98, 98, 98);\n"
"}")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_8.setStyleSheet("QGroupBox\n"
"{\n"
"border:0px;\n"
"}")
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(124, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_fengsu = QtWidgets.QLabel(self.groupBox_8)
        self.label_fengsu.setMinimumSize(QtCore.QSize(120, 0))
        self.label_fengsu.setMaximumSize(QtCore.QSize(7777, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_fengsu.setFont(font)
        self.label_fengsu.setObjectName("label_fengsu")
        self.horizontalLayout_3.addWidget(self.label_fengsu)
        self.label_fengya = QtWidgets.QLabel(self.groupBox_8)
        self.label_fengya.setMinimumSize(QtCore.QSize(120, 0))
        self.label_fengya.setMaximumSize(QtCore.QSize(66666, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_fengya.setFont(font)
        self.label_fengya.setObjectName("label_fengya")
        self.horizontalLayout_3.addWidget(self.label_fengya)
        self.label_fengsang = QtWidgets.QLabel(self.groupBox_8)
        self.label_fengsang.setMinimumSize(QtCore.QSize(120, 0))
        self.label_fengsang.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_fengsang.setFont(font)
        self.label_fengsang.setObjectName("label_fengsang")
        self.horizontalLayout_3.addWidget(self.label_fengsang)
        self.label_pm2_5 = QtWidgets.QLabel(self.groupBox_8)
        self.label_pm2_5.setMaximumSize(QtCore.QSize(333333, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_pm2_5.setFont(font)
        self.label_pm2_5.setObjectName("label_pm2_5")
        self.horizontalLayout_3.addWidget(self.label_pm2_5)
        spacerItem3 = QtWidgets.QSpacerItem(193, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_4.addWidget(self.groupBox_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.pushButton_mic = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_mic.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_mic.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton_mic.setText("")
        self.pushButton_mic.setObjectName("pushButton_mic")
        self.horizontalLayout_10.addWidget(self.pushButton_mic)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.groupBox_fjdw = QtWidgets.QGroupBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_fjdw.setFont(font)
        self.groupBox_fjdw.setObjectName("groupBox_fjdw")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_fjdw)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.radioButton_fjdw_close = QtWidgets.QRadioButton(self.groupBox_fjdw)
        self.radioButton_fjdw_close.setMinimumSize(QtCore.QSize(100, 50))
        self.radioButton_fjdw_close.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_fjdw_close.setFont(font)
        self.radioButton_fjdw_close.setStyleSheet("")
        self.radioButton_fjdw_close.setObjectName("radioButton_fjdw_close")
        self.horizontalLayout_8.addWidget(self.radioButton_fjdw_close)
        self.radioButton_fjdw_1d = QtWidgets.QRadioButton(self.groupBox_fjdw)
        self.radioButton_fjdw_1d.setMinimumSize(QtCore.QSize(100, 50))
        self.radioButton_fjdw_1d.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_fjdw_1d.setFont(font)
        self.radioButton_fjdw_1d.setStyleSheet("")
        self.radioButton_fjdw_1d.setChecked(True)
        self.radioButton_fjdw_1d.setObjectName("radioButton_fjdw_1d")
        self.horizontalLayout_8.addWidget(self.radioButton_fjdw_1d)
        self.radioButton_fjdw_2d = QtWidgets.QRadioButton(self.groupBox_fjdw)
        self.radioButton_fjdw_2d.setMinimumSize(QtCore.QSize(100, 50))
        self.radioButton_fjdw_2d.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_fjdw_2d.setFont(font)
        self.radioButton_fjdw_2d.setStyleSheet("")
        self.radioButton_fjdw_2d.setObjectName("radioButton_fjdw_2d")
        self.horizontalLayout_8.addWidget(self.radioButton_fjdw_2d)
        self.radioButton_fjdw_3d = QtWidgets.QRadioButton(self.groupBox_fjdw)
        self.radioButton_fjdw_3d.setMinimumSize(QtCore.QSize(100, 50))
        self.radioButton_fjdw_3d.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_fjdw_3d.setFont(font)
        self.radioButton_fjdw_3d.setStyleSheet("")
        self.radioButton_fjdw_3d.setObjectName("radioButton_fjdw_3d")
        self.horizontalLayout_8.addWidget(self.radioButton_fjdw_3d)
        self.radioButton_fjdw_4d = QtWidgets.QRadioButton(self.groupBox_fjdw)
        self.radioButton_fjdw_4d.setMinimumSize(QtCore.QSize(100, 50))
        self.radioButton_fjdw_4d.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_fjdw_4d.setFont(font)
        self.radioButton_fjdw_4d.setStyleSheet("")
        self.radioButton_fjdw_4d.setObjectName("radioButton_fjdw_4d")
        self.horizontalLayout_8.addWidget(self.radioButton_fjdw_4d)
        self.radioButton_fjdw_5d = QtWidgets.QRadioButton(self.groupBox_fjdw)
        self.radioButton_fjdw_5d.setMinimumSize(QtCore.QSize(100, 50))
        self.radioButton_fjdw_5d.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_fjdw_5d.setFont(font)
        self.radioButton_fjdw_5d.setStyleSheet("")
        self.radioButton_fjdw_5d.setObjectName("radioButton_fjdw_5d")
        self.horizontalLayout_8.addWidget(self.radioButton_fjdw_5d)
        self.horizontalLayout_10.addWidget(self.groupBox_fjdw)
        self.groupBox_dbyd = QtWidgets.QGroupBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox_dbyd.setFont(font)
        self.groupBox_dbyd.setObjectName("groupBox_dbyd")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_dbyd)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.radioButton_dbyd_open = QtWidgets.QRadioButton(self.groupBox_dbyd)
        self.radioButton_dbyd_open.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_dbyd_open.setFont(font)
        self.radioButton_dbyd_open.setChecked(True)
        self.radioButton_dbyd_open.setObjectName("radioButton_dbyd_open")
        self.horizontalLayout_9.addWidget(self.radioButton_dbyd_open)
        self.radioButton_dbyd_close = QtWidgets.QRadioButton(self.groupBox_dbyd)
        self.radioButton_dbyd_close.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_dbyd_close.setFont(font)
        self.radioButton_dbyd_close.setObjectName("radioButton_dbyd_close")
        self.horizontalLayout_9.addWidget(self.radioButton_dbyd_close)
        self.horizontalLayout_10.addWidget(self.groupBox_dbyd)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 2)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setStyleSheet("QGroupBox\n"
"{\n"
"   border-color: rgb(98, 98, 98);\n"
"}")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_4)
        self.tabWidget.setStyleSheet("QTabWidget::tab-bar\n"
"{\n"
"    height:0px;\n"
"}\n"
" \n"
"QTabWidget::pane\n"
"{\n"
"     border-top-width: 0px transparent;\n"
"     border-right-width: 0px transparent;\n"
"     border-bottom-width: 0px transparent;\n"
"     border-left-width: 0px transparent;\n"
"     top: -1.6em;\n"
"}")
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_main = QtWidgets.QWidget()
        self.tab_main.setObjectName("tab_main")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_main)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.tab_main)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem7 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.verticalSlider_sx_1 = QtWidgets.QSlider(self.tab_main)
        self.verticalSlider_sx_1.setMinimumSize(QtCore.QSize(50, 0))
        self.verticalSlider_sx_1.setMaximum(100)
        self.verticalSlider_sx_1.setProperty("value", 0)
        self.verticalSlider_sx_1.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_sx_1.setObjectName("verticalSlider_sx_1")
        self.horizontalLayout_5.addWidget(self.verticalSlider_sx_1)
        spacerItem8 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.label_8 = QtWidgets.QLabel(self.tab_main)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.label_sx_1 = QtWidgets.QLabel(self.tab_main)
        self.label_sx_1.setMinimumSize(QtCore.QSize(85, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_sx_1.setFont(font)
        self.label_sx_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sx_1.setObjectName("label_sx_1")
        self.verticalLayout_5.addWidget(self.label_sx_1)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.label_gif = QtWidgets.QLabel(self.tab_main)
        self.label_gif.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_gif.setText("")
        self.label_gif.setObjectName("label_gif")
        self.horizontalLayout_7.addWidget(self.label_gif)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.tab_main)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem9 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.verticalSlider_sx_2 = QtWidgets.QSlider(self.tab_main)
        self.verticalSlider_sx_2.setMinimumSize(QtCore.QSize(50, 50))
        self.verticalSlider_sx_2.setMaximum(100)
        self.verticalSlider_sx_2.setProperty("value", 50)
        self.verticalSlider_sx_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_sx_2.setObjectName("verticalSlider_sx_2")
        self.horizontalLayout_6.addWidget(self.verticalSlider_sx_2)
        spacerItem10 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.label_10 = QtWidgets.QLabel(self.tab_main)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.label_10)
        self.label_sx_2 = QtWidgets.QLabel(self.tab_main)
        self.label_sx_2.setMinimumSize(QtCore.QSize(85, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_sx_2.setFont(font)
        self.label_sx_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sx_2.setObjectName("label_sx_2")
        self.verticalLayout_6.addWidget(self.label_sx_2)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.horizontalLayout_7.setStretch(1, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_left = QtWidgets.QGroupBox(self.tab_main)
        self.groupBox_left.setTitle("")
        self.groupBox_left.setObjectName("groupBox_left")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox_left)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.radioButton_sf_1 = QtWidgets.QRadioButton(self.groupBox_left)
        self.radioButton_sf_1.setMinimumSize(QtCore.QSize(100, 50))
        self.radioButton_sf_1.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_sf_1.setFont(font)
        self.radioButton_sf_1.setObjectName("radioButton_sf_1")
        self.horizontalLayout_11.addWidget(self.radioButton_sf_1)
        self.radioButton_brc_1 = QtWidgets.QRadioButton(self.groupBox_left)
        self.radioButton_brc_1.setMinimumSize(QtCore.QSize(100, 50))
        self.radioButton_brc_1.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_brc_1.setFont(font)
        self.radioButton_brc_1.setChecked(True)
        self.radioButton_brc_1.setObjectName("radioButton_brc_1")
        self.horizontalLayout_11.addWidget(self.radioButton_brc_1)
        self.radioButton_drc_1 = QtWidgets.QRadioButton(self.groupBox_left)
        self.radioButton_drc_1.setMinimumSize(QtCore.QSize(100, 50))
        self.radioButton_drc_1.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_drc_1.setFont(font)
        self.radioButton_drc_1.setObjectName("radioButton_drc_1")
        self.horizontalLayout_11.addWidget(self.radioButton_drc_1)
        self.radioButton_close_left = QtWidgets.QRadioButton(self.groupBox_left)
        self.radioButton_close_left.setMinimumSize(QtCore.QSize(100, 50))
        self.radioButton_close_left.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_close_left.setFont(font)
        self.radioButton_close_left.setObjectName("radioButton_close_left")
        self.horizontalLayout_11.addWidget(self.radioButton_close_left)
        self.verticalLayout_7.addWidget(self.groupBox_left)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_12 = QtWidgets.QLabel(self.tab_main)
        self.label_12.setMaximumSize(QtCore.QSize(16, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_13.addWidget(self.label_12)
        self.horizontalSlider_left_bottom = QtWidgets.QSlider(self.tab_main)
        self.horizontalSlider_left_bottom.setMinimumSize(QtCore.QSize(500, 60))
        self.horizontalSlider_left_bottom.setMaximum(115)
        self.horizontalSlider_left_bottom.setProperty("value", 50)
        self.horizontalSlider_left_bottom.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_left_bottom.setInvertedAppearance(False)
        self.horizontalSlider_left_bottom.setObjectName("horizontalSlider_left_bottom")
        self.horizontalLayout_13.addWidget(self.horizontalSlider_left_bottom)
        self.label_13 = QtWidgets.QLabel(self.tab_main)
        self.label_13.setMaximumSize(QtCore.QSize(31, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_13.addWidget(self.label_13)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.label_zy_left = QtWidgets.QLabel(self.tab_main)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_zy_left.setFont(font)
        self.label_zy_left.setAlignment(QtCore.Qt.AlignCenter)
        self.label_zy_left.setObjectName("label_zy_left")
        self.verticalLayout_7.addWidget(self.label_zy_left)
        self.horizontalLayout_15.addLayout(self.verticalLayout_7)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem11)
        self.pushButton_link = QtWidgets.QPushButton(self.tab_main)
        self.pushButton_link.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_link.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton_link.setText("")
        self.pushButton_link.setObjectName("pushButton_link")
        self.horizontalLayout_15.addWidget(self.pushButton_link)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem12)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_right = QtWidgets.QGroupBox(self.tab_main)
        self.groupBox_right.setTitle("")
        self.groupBox_right.setObjectName("groupBox_right")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.groupBox_right)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.radioButton_close_right = QtWidgets.QRadioButton(self.groupBox_right)
        self.radioButton_close_right.setMinimumSize(QtCore.QSize(100, 50))
        self.radioButton_close_right.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_close_right.setFont(font)
        self.radioButton_close_right.setObjectName("radioButton_close_right")
        self.horizontalLayout_12.addWidget(self.radioButton_close_right)
        self.radioButton_drc_2 = QtWidgets.QRadioButton(self.groupBox_right)
        self.radioButton_drc_2.setMinimumSize(QtCore.QSize(100, 50))
        self.radioButton_drc_2.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_drc_2.setFont(font)
        self.radioButton_drc_2.setObjectName("radioButton_drc_2")
        self.horizontalLayout_12.addWidget(self.radioButton_drc_2)
        self.radioButton_brc_2 = QtWidgets.QRadioButton(self.groupBox_right)
        self.radioButton_brc_2.setMinimumSize(QtCore.QSize(100, 50))
        self.radioButton_brc_2.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_brc_2.setFont(font)
        self.radioButton_brc_2.setChecked(True)
        self.radioButton_brc_2.setObjectName("radioButton_brc_2")
        self.horizontalLayout_12.addWidget(self.radioButton_brc_2)
        self.radioButton_sf_2 = QtWidgets.QRadioButton(self.groupBox_right)
        self.radioButton_sf_2.setMinimumSize(QtCore.QSize(100, 50))
        self.radioButton_sf_2.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_sf_2.setFont(font)
        self.radioButton_sf_2.setObjectName("radioButton_sf_2")
        self.horizontalLayout_12.addWidget(self.radioButton_sf_2)
        self.verticalLayout_8.addWidget(self.groupBox_right)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_14 = QtWidgets.QLabel(self.tab_main)
        self.label_14.setMaximumSize(QtCore.QSize(16, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_14.addWidget(self.label_14)
        self.horizontalSlider_right_bottom = QtWidgets.QSlider(self.tab_main)
        self.horizontalSlider_right_bottom.setMinimumSize(QtCore.QSize(500, 50))
        self.horizontalSlider_right_bottom.setMaximum(115)
        self.horizontalSlider_right_bottom.setProperty("value", 50)
        self.horizontalSlider_right_bottom.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_right_bottom.setObjectName("horizontalSlider_right_bottom")
        self.horizontalLayout_14.addWidget(self.horizontalSlider_right_bottom)
        self.label_15 = QtWidgets.QLabel(self.tab_main)
        self.label_15.setMaximumSize(QtCore.QSize(31, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_14.addWidget(self.label_15)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.label_zy_right = QtWidgets.QLabel(self.tab_main)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_zy_right.setFont(font)
        self.label_zy_right.setAlignment(QtCore.Qt.AlignCenter)
        self.label_zy_right.setObjectName("label_zy_right")
        self.verticalLayout_8.addWidget(self.label_zy_right)
        self.horizontalLayout_15.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_15)
        self.verticalLayout_9.setStretch(0, 4)
        self.verticalLayout_9.setStretch(1, 1)
        self.tabWidget.addTab(self.tab_main, "")
        self.tab_light = QtWidgets.QWidget()
        self.tab_light.setObjectName("tab_light")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.tab_light)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(-1, 30, -1, -1)
        self.verticalLayout_10.setSpacing(50)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_16 = QtWidgets.QLabel(self.tab_light)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_16.addWidget(self.label_16)
        self.horizontalSlider_red = QtWidgets.QSlider(self.tab_light)
        self.horizontalSlider_red.setMinimumSize(QtCore.QSize(700, 60))
        self.horizontalSlider_red.setMaximum(255)
        self.horizontalSlider_red.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_red.setObjectName("horizontalSlider_red")
        self.horizontalLayout_16.addWidget(self.horizontalSlider_red)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_17 = QtWidgets.QLabel(self.tab_light)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_17.addWidget(self.label_17)
        self.horizontalSlider_green = QtWidgets.QSlider(self.tab_light)
        self.horizontalSlider_green.setMinimumSize(QtCore.QSize(700, 60))
        self.horizontalSlider_green.setMaximum(255)
        self.horizontalSlider_green.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_green.setObjectName("horizontalSlider_green")
        self.horizontalLayout_17.addWidget(self.horizontalSlider_green)
        self.verticalLayout_10.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_18 = QtWidgets.QLabel(self.tab_light)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_18.addWidget(self.label_18)
        self.horizontalSlider_blue = QtWidgets.QSlider(self.tab_light)
        self.horizontalSlider_blue.setMinimumSize(QtCore.QSize(700, 60))
        self.horizontalSlider_blue.setMaximum(255)
        self.horizontalSlider_blue.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_blue.setObjectName("horizontalSlider_blue")
        self.horizontalLayout_18.addWidget(self.horizontalSlider_blue)
        self.verticalLayout_10.addLayout(self.horizontalLayout_18)
        self.groupBox_jdms = QtWidgets.QGroupBox(self.tab_light)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_jdms.setFont(font)
        self.groupBox_jdms.setObjectName("groupBox_jdms")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.groupBox_jdms)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.radioButton_jdms = QtWidgets.QRadioButton(self.groupBox_jdms)
        self.radioButton_jdms.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_jdms.setFont(font)
        self.radioButton_jdms.setChecked(True)
        self.radioButton_jdms.setObjectName("radioButton_jdms")
        self.horizontalLayout_20.addWidget(self.radioButton_jdms)
        self.radioButton_hxms = QtWidgets.QRadioButton(self.groupBox_jdms)
        self.radioButton_hxms.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_hxms.setFont(font)
        self.radioButton_hxms.setObjectName("radioButton_hxms")
        self.horizontalLayout_20.addWidget(self.radioButton_hxms)
        self.radioButton_fsms = QtWidgets.QRadioButton(self.groupBox_jdms)
        self.radioButton_fsms.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_fsms.setFont(font)
        self.radioButton_fsms.setObjectName("radioButton_fsms")
        self.horizontalLayout_20.addWidget(self.radioButton_fsms)
        self.radioButton_fwms = QtWidgets.QRadioButton(self.groupBox_jdms)
        self.radioButton_fwms.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_fwms.setFont(font)
        self.radioButton_fwms.setObjectName("radioButton_fwms")
        self.horizontalLayout_20.addWidget(self.radioButton_fwms)
        self.radioButton_ldms = QtWidgets.QRadioButton(self.groupBox_jdms)
        self.radioButton_ldms.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_ldms.setFont(font)
        self.radioButton_ldms.setObjectName("radioButton_ldms")
        self.horizontalLayout_20.addWidget(self.radioButton_ldms)
        self.verticalLayout_10.addWidget(self.groupBox_jdms)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem13)
        self.horizontalLayout_19.addLayout(self.verticalLayout_10)
        spacerItem14 = QtWidgets.QSpacerItem(466, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem14)
        self.tabWidget.addTab(self.tab_light, "")
        self.tab_tempature = QtWidgets.QWidget()
        self.tab_tempature.setObjectName("tab_tempature")
        self.layoutWidget = QtWidgets.QWidget(self.tab_tempature)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 110, 596, 52))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        self.label_19.setMaximumSize(QtCore.QSize(41, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_21.addWidget(self.label_19)
        self.horizontalSlider_cold_hot = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSlider_cold_hot.setMinimumSize(QtCore.QSize(500, 50))
        self.horizontalSlider_cold_hot.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_cold_hot.setObjectName("horizontalSlider_cold_hot")
        self.horizontalLayout_21.addWidget(self.horizontalSlider_cold_hot)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        self.label_20.setMaximumSize(QtCore.QSize(41, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_21.addWidget(self.label_20)
        self.tabWidget.addTab(self.tab_tempature, "")
        self.horizontalLayout_4.addWidget(self.tabWidget)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_reserve.setText(_translate("Form", "预留"))
        self.label_fengsu.setText(_translate("Form", "风速：-- m/s"))
        self.label_fengya.setText(_translate("Form", "风压：-- pka"))
        self.label_fengsang.setText(_translate("Form", "风嗓：-- db"))
        self.label_pm2_5.setText(_translate("Form", "PM2_5:-- ug/m^3"))
        self.groupBox_fjdw.setTitle(_translate("Form", "风机档位"))
        self.radioButton_fjdw_close.setText(_translate("Form", "关闭"))
        self.radioButton_fjdw_1d.setText(_translate("Form", "1挡"))
        self.radioButton_fjdw_2d.setText(_translate("Form", "2挡"))
        self.radioButton_fjdw_3d.setText(_translate("Form", "3挡"))
        self.radioButton_fjdw_4d.setText(_translate("Form", "4挡"))
        self.radioButton_fjdw_5d.setText(_translate("Form", "5挡"))
        self.groupBox_dbyd.setTitle(_translate("Form", "挡板运动"))
        self.radioButton_dbyd_open.setText(_translate("Form", "开启"))
        self.radioButton_dbyd_close.setText(_translate("Form", "关闭"))
        self.label_9.setText(_translate("Form", "100"))
        self.label_8.setText(_translate("Form", "0"))
        self.label_sx_1.setText(_translate("Form", "上下：---度"))
        self.label_11.setText(_translate("Form", "100"))
        self.label_10.setText(_translate("Form", "0"))
        self.label_sx_2.setText(_translate("Form", "上下：---度"))
        self.radioButton_sf_1.setText(_translate("Form", "扫风"))
        self.radioButton_brc_1.setText(_translate("Form", "避人吹"))
        self.radioButton_drc_1.setText(_translate("Form", "对人吹"))
        self.radioButton_close_left.setText(_translate("Form", "关闭"))
        self.label_12.setText(_translate("Form", "0"))
        self.label_13.setText(_translate("Form", "115"))
        self.label_zy_left.setText(_translate("Form", "左右：---度"))
        self.radioButton_close_right.setText(_translate("Form", "关闭"))
        self.radioButton_drc_2.setText(_translate("Form", "对人吹"))
        self.radioButton_brc_2.setText(_translate("Form", "避人吹"))
        self.radioButton_sf_2.setText(_translate("Form", "扫风"))
        self.label_14.setText(_translate("Form", "0"))
        self.label_15.setText(_translate("Form", "115"))
        self.label_zy_right.setText(_translate("Form", "左右：----度"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_main), _translate("Form", "2321"))
        self.label_16.setText(_translate("Form", "红色"))
        self.label_17.setText(_translate("Form", "绿色"))
        self.label_18.setText(_translate("Form", "蓝色"))
        self.groupBox_jdms.setTitle(_translate("Form", "变换方式"))
        self.radioButton_jdms.setText(_translate("Form", "经典模式"))
        self.radioButton_hxms.setText(_translate("Form", "呼吸模式"))
        self.radioButton_fsms.setText(_translate("Form", "风速模式"))
        self.radioButton_fwms.setText(_translate("Form", "风温模式"))
        self.radioButton_ldms.setText(_translate("Form", "律动模式"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_light), _translate("Form", "Tab 2"))
        self.label_19.setText(_translate("Form", "冷风"))
        self.label_20.setText(_translate("Form", "热风"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tempature), _translate("Form", "页"))

